# Problem Statement

## People spend a lot of time reading long documents, articles, or reports. This project automatically generates a short summary containing the main points.

# objectives
### * Generate summaries from long text.
### * Reduce reading time.
### * Use a Transformer model.
### * Create a simple web interface.

# Literature Review

#### Text summarization is a Natural Language Processing (NLP) task that automatically generates a concise and meaningful summary from a long piece of text while preserving its main ideas. It helps users quickly understand the key information without reading the entire document. Text summarization is widely used in news websites, research paper analysis, business reports, legal documents, and educational applications.

#### Traditional text summarization methods relied on extractive techniques, where important sentences were selected directly from the original text. Although these methods are simple, they often produce summaries that are less coherent and may contain redundant information.

#### Recent advancements in Deep Learning and Transformer architectures have significantly improved text summarization. Transformer-based models understand the context and relationships between words more effectively than traditional approaches. Models such as BART, T5, and PEGASUS are widely used for abstractive text summarization because they can generate new sentences that accurately represent the meaning of the original text.

#### Among these models, BART (Bidirectional and Auto-Regressive Transformers) has shown excellent performance on benchmark datasets such as CNN/DailyMail and XSum. BART combines bidirectional encoding with autoregressive decoding, enabling it to generate fluent and high-quality summaries.

#### In this project, a pre-trained BART model from the Hugging Face Transformers library is used. Using a pre-trained model reduces training time while maintaining high summarization quality. The project also uses Streamlit to provide a simple and user-friendly web interface where users can enter text and receive an AI-generated summary.

#### Overall, Transformer-based text summarization provides an efficient solution for reducing reading time while preserving the essential information contained in long documents.

In [15]:
import sys
!{sys.executable} -m pip install datasets==2.21.0 huggingface_hub==0.24.7

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets==2.21.0 in .\AppData\Roaming\Python\Python313\site-packages (2.21.0)
Requirement already satisfied: huggingface_hub==0.24.7 in .\AppData\Roaming\Python\Python313\site-packages (0.24.7)
Requirement already satisfied: filelock in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (3.17.0)
Requirement already satisfied: numpy>=1.17 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (2.1.3)
Requirement already satisfied: pyarrow>=15.0.0 in .\AppData\Roaming\Python\Python313\site-packages (from datasets==2.21.0) (24.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in .\AppData\Roaming\Python\Python313\site-packages (from datasets==2.21.0) (0.3.8)
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (4.67.1)
Requirement already satisfied: xxhash in .\AppData\Roaming\Python\Python313\site-packages (from datasets==2.21.0) (3.8.0)
Requirement already satisfied: multiprocess in .\AppData\Roaming\Python\Python313\site-packages (from datasets==2.21.0) (0.70.16)
Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in .\AppData\Roaming\Python\Python313\site-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets==2.21.0) (2024.6.1)
Requirement already satisfied: aiohttp in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (3.11.10)
Requirement already satisfied: packaging in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface_hub==0.24.7) (4.12.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (1.18.0)
Requirement already satisfied: idna>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp->datasets==2.21.0) (3.7)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets==2.21.0) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets==2.21.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets==2.21.0) (2025.4.26)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from tqdm>=4.66.3->datasets==2.21.0) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->datasets==2.21.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->datasets==2.21.0) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->datasets==2.21.0) (2025.2)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets==2.21.0) (1.17.0)

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

In [14]:
import sys

!{sys.executable} -m pip uninstall -y huggingface_hub datasets
!{sys.executable} -m pip install datasets==2.21.0 huggingface_hub==0.24.7

Found existing installation: huggingface-hub 0.24.7
Uninstalling huggingface-hub-0.24.7:
  Successfully uninstalled huggingface-hub-0.24.7
Found existing installation: datasets 2.21.0
Uninstalling datasets-2.21.0:
  Successfully uninstalled datasets-2.21.0

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

Defaulting to user installation because normal site-packages is not writeable
Collecting datasets==2.21.0
  Using cached datasets-2.21.0-py3-none-any.whl.metadata (21 kB)
Collecting huggingface_hub==0.24.7
  Using cached huggingface_hub-0.24.7-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (3.17.0)
Requirement already satisfied: numpy>=1.17 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (2.1.3)
Requirement already satisfied: pyarrow>=15.0.0 in .\AppData\Roaming\Python\Python313\site-packages (from datasets==2.21.0) (24.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in .\AppData\Roaming\Python\Python313\site-packages (from datasets==2.21.0) (0.3.8)
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (4.67.1)
Requirement already satisfied: xxhash in .\AppData\Roaming\Python\Python313\site-packages (from datasets==2.21.0) (3.8.0)
Requirement already satisfied: multiprocess in .\AppData\Roaming\Python\Python313\site-packages (from datasets==2.21.0) (0.70.16)
Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in .\AppData\Roaming\Python\Python313\site-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets==2.21.0) (2024.6.1)
Requirement already satisfied: aiohttp in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (3.11.10)
Requirement already satisfied: packaging in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets==2.21.0) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface_hub==0.24.7) (4.12.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets==2.21.0) (1.18.0)
Requirement already satisfied: idna>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp->datasets==2.21.0) (3.7)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets==2.21.0) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets==2.21.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.32.2->datasets==2.21.0) (2025.4.26)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from tqdm>=4.66.3->datasets==2.21.0) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->datasets==2.21.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->datasets==2.21.0) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->datasets==2.21.0) (2025.2)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets==2.21.0) (1.17.0)
Using cached datasets-2.21.0-py3-none-any.whl (527 kB)
Using cached huggingface_hub-0.24.7-py3-none-any.whl (417 kB)
Installing collected packages: huggingface_hub, datasets

   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   ---------------------------------------- 0/2 [huggingface_hub]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   -------------------- ------------------- 1/2 [datasets]
   ---------------------------------------- 2/2 [datasets]

Successfully installed datasets-2.21.0 huggingface_hub-0.24.7

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
  WARNING: The script huggingface-cli.exe is installed in 'C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script datasets-cli.exe is installed in 'C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

In [13]:
from datasets import load_dataset

In [9]:
from datasets import load_dataset

dataset = load_dataset("cnn_dailymail", "3.0.0")
print(dataset)

Using the latest cached version of the dataset since cnn_dailymail couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration '3.0.0' at C:\Users\MOHAMMED SIYAN\.cache\huggingface\datasets\cnn_dailymail\3.0.0\0.0.0\96df5e686bee6baa90b8bee7c28b81fa3fa6223d (last modified on Mon Jul  6 12:58:09 2026).

DatasetDict({
    train: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 287113
    })
    validation: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 13368
    })
    test: Dataset({
        features: ['article', 'highlights', 'id'],
        num_rows: 11490
    })
})

In [10]:
print(dataset["train"][0]["article"])

LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don't think I'll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how he'll mark his landmark birthday are under wraps. His agent and publicist had no comment on his plans. "I'll definitely have some sort of party," he said in an interview. "Hopefully none of you will be reading about it." Radcliffe's earnings from the first five Potter films have been held in a trust fund which he has not been able to touch. Despite his growing fame and riches, the actor says he is keeping his feet firmly on the ground. "People are always looking to say 'kid star goes off the rails,'" he told reporters last month. "But I try very hard not to go that way because it would be too easy for them." His latest outing as the boy wizard in "Harry Potter and the Order of the Phoenix" is breaking records on both sides of the Atlantic and he will reprise the role in the last two films.  Watch I-Reporter give her review of Potter's latest » . There is life beyond Potter, however. The Londoner has filmed a TV movie called "My Boy Jack," about author Rudyard Kipling and his son, due for release later this year. He will also appear in "December Boys," an Australian film about four boys who escape an orphanage. Earlier this year, he made his stage debut playing a tortured teenager in Peter Shaffer's "Equus." Meanwhile, he is braced for even closer media scrutiny now that he's legally an adult: "I just think I'm going to be more sort of fair game," he told Reuters. E-mail to a friend . Copyright 2007 Reuters. All rights reserved.This material may not be published, broadcast, rewritten, or redistributed.

In [11]:
print(dataset["train"][0]["highlights"])

Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday .
Young actor says he has no plans to fritter his cash away .
Radcliffe's earnings from first five Potter films have been held in trust fund .

In [12]:
import pandas as pd

df = pd.DataFrame(dataset["train"])
df.head()

,article,highlights,id
0,"LONDON, England (Reuters) -- Harry Potter star...",Harry Potter star Daniel Radcliffe gets £20M f...,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4
1,Editor's note: In our Behind the Scenes series...,Mentally ill inmates in Miami are housed on th...,ee8871b15c50d0db17b0179a6d2beab35065f1e9
2,"MINNEAPOLIS, Minnesota (CNN) -- Drivers who we...","NEW: ""I thought I was going to die,"" driver sa...",06352019a19ae31e527f37f7571c6dd7f0c5da37
3,WASHINGTON (CNN) -- Doctors removed five small...,"Five small polyps found during procedure; ""non...",24521a2abb2e1f5e34e6824e0f9e56904a2b0e88
4,(CNN) -- The National Football League has ind...,"NEW: NFL chief, Atlanta Falcons owner critical...",7fe70cc8b12fab2d0a258fababf7d9c6b5e1262a

In [13]:
df.to_csv("cnn_dailymail_train.csv", index=False)
print("Dataset saved successfully!")

Dataset saved successfully!

In [14]:
print(df.columns)

Index(['article', 'highlights', 'id'], dtype='object')

## Text Summarization Project Roadmap

1. Introduction
2. Import Libraries
3. Load Dataset  (Completed)
4. Exploratory Data Analysis (EDA)
5. Data Preprocessing
6. Model Building
7. Train Model
8. Generate Summary
9. Evaluate Model
10. Streamlit Web App

In [15]:
## Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from datasets import load_dataset

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [16]:
## View Dataset
df.head()

,article,highlights,id
0,"LONDON, England (Reuters) -- Harry Potter star...",Harry Potter star Daniel Radcliffe gets £20M f...,42c027e4ff9730fbb3de84c1af0d2c506e41c3e4
1,Editor's note: In our Behind the Scenes series...,Mentally ill inmates in Miami are housed on th...,ee8871b15c50d0db17b0179a6d2beab35065f1e9
2,"MINNEAPOLIS, Minnesota (CNN) -- Drivers who we...","NEW: ""I thought I was going to die,"" driver sa...",06352019a19ae31e527f37f7571c6dd7f0c5da37
3,WASHINGTON (CNN) -- Doctors removed five small...,"Five small polyps found during procedure; ""non...",24521a2abb2e1f5e34e6824e0f9e56904a2b0e88
4,(CNN) -- The National Football League has ind...,"NEW: NFL chief, Atlanta Falcons owner critical...",7fe70cc8b12fab2d0a258fababf7d9c6b5e1262a

In [17]:
## Dataset Shape
print(df.shape)

(287113, 3)

In [18]:
## Dataset Shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287113 entries, 0 to 287112
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   article     287113 non-null  object
 1   highlights  287113 non-null  object
 2   id          287113 non-null  object
dtypes: object(3)
memory usage: 6.6+ MB

In [19]:
## Missing Values
df.isnull().sum()

article       0
highlights    0
id            0
dtype: int64

In [20]:
## Display One Article
print(df["article"][0])

LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don't think I'll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how he'll mark his landmark birthday are under wraps. His agent and publicist had no comment on his plans. "I'll definitely have some sort of party," he said in an interview. "Hopefully none of you will be reading about it." Radcliffe's earnings from the first five Potter films have been held in a trust fund which he has not been able to touch. Despite his growing fame and riches, the actor says he is keeping his feet firmly on the ground. "People are always looking to say 'kid star goes off the rails,'" he told reporters last month. "But I try very hard not to go that way because it would be too easy for them." His latest outing as the boy wizard in "Harry Potter and the Order of the Phoenix" is breaking records on both sides of the Atlantic and he will reprise the role in the last two films.  Watch I-Reporter give her review of Potter's latest » . There is life beyond Potter, however. The Londoner has filmed a TV movie called "My Boy Jack," about author Rudyard Kipling and his son, due for release later this year. He will also appear in "December Boys," an Australian film about four boys who escape an orphanage. Earlier this year, he made his stage debut playing a tortured teenager in Peter Shaffer's "Equus." Meanwhile, he is braced for even closer media scrutiny now that he's legally an adult: "I just think I'm going to be more sort of fair game," he told Reuters. E-mail to a friend . Copyright 2007 Reuters. All rights reserved.This material may not be published, broadcast, rewritten, or redistributed.

In [21]:
## Display Its Summary
print(df["highlights"][0])

Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday .
Young actor says he has no plans to fritter his cash away .
Radcliffe's earnings from first five Potter films have been held in trust fund .

In [22]:
## Check One Article Before Cleaning

print(df["article"][0])

LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don't think I'll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how he'll mark his landmark birthday are under wraps. His agent and publicist had no comment on his plans. "I'll definitely have some sort of party," he said in an interview. "Hopefully none of you will be reading about it." Radcliffe's earnings from the first five Potter films have been held in a trust fund which he has not been able to touch. Despite his growing fame and riches, the actor says he is keeping his feet firmly on the ground. "People are always looking to say 'kid star goes off the rails,'" he told reporters last month. "But I try very hard not to go that way because it would be too easy for them." His latest outing as the boy wizard in "Harry Potter and the Order of the Phoenix" is breaking records on both sides of the Atlantic and he will reprise the role in the last two films.  Watch I-Reporter give her review of Potter's latest » . There is life beyond Potter, however. The Londoner has filmed a TV movie called "My Boy Jack," about author Rudyard Kipling and his son, due for release later this year. He will also appear in "December Boys," an Australian film about four boys who escape an orphanage. Earlier this year, he made his stage debut playing a tortured teenager in Peter Shaffer's "Equus." Meanwhile, he is braced for even closer media scrutiny now that he's legally an adult: "I just think I'm going to be more sort of fair game," he told Reuters. E-mail to a friend . Copyright 2007 Reuters. All rights reserved.This material may not be published, broadcast, rewritten, or redistributed.

In [23]:
## Import Regular Expression Library
import re

In [24]:
## Create a Cleaning Function
def clean_text(text):
    text = re.sub(r"<.*?>", "", text)
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    text = text.lower()
    text = text.strip()
    return text

In [25]:
## Clean the Articles
df["clean_article"] = df["article"].apply(clean_text)

In [26]:
## Clean the Summaries
df["clean_summary"] = df["highlights"].apply(clean_text)

In [27]:
## Compare Original vs Cleaned
print("Original Article")
print(df["article"][0])

print("\n" + "="*80 + "\n")

print("Cleaned Article")
print(df["clean_article"][0])

Original Article
LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don't think I'll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how he'll mark his landmark birthday are under wraps. His agent and publicist had no comment on his plans. "I'll definitely have some sort of party," he said in an interview. "Hopefully none of you will be reading about it." Radcliffe's earnings from the first five Potter films have been held in a trust fund which he has not been able to touch. Despite his growing fame and riches, the actor says he is keeping his feet firmly on the ground. "People are always looking to say 'kid star goes off the rails,'" he told reporters last month. "But I try very hard not to go that way because it would be too easy for them." His latest outing as the boy wizard in "Harry Potter and the Order of the Phoenix" is breaking records on both sides of the Atlantic and he will reprise the role in the last two films.  Watch I-Reporter give her review of Potter's latest » . There is life beyond Potter, however. The Londoner has filmed a TV movie called "My Boy Jack," about author Rudyard Kipling and his son, due for release later this year. He will also appear in "December Boys," an Australian film about four boys who escape an orphanage. Earlier this year, he made his stage debut playing a tortured teenager in Peter Shaffer's "Equus." Meanwhile, he is braced for even closer media scrutiny now that he's legally an adult: "I just think I'm going to be more sort of fair game," he told Reuters. E-mail to a friend . Copyright 2007 Reuters. All rights reserved.This material may not be published, broadcast, rewritten, or redistributed.

================================================================================

Cleaned Article
london england reuters  harry potter star daniel radcliffe gains access to a reported 20 million 411 million fortune as he turns 18 on monday but he insists the money wont cast a spell on him daniel radcliffe as harry potter in harry potter and the order of the phoenix to the disappointment of gossip columnists around the world the young actor says he has no plans to fritter his cash away on fast cars drink and celebrity parties i dont plan to be one of those people who as soon as they turn 18 suddenly buy themselves a massive sports car collection or something similar he told an australian interviewer earlier this month i dont think ill be particularly extravagant the things i like buying are things that cost about 10 pounds  books and cds and dvds at 18 radcliffe will be able to gamble in a casino buy a drink in a pub or see the horror film hostel part ii currently six places below his number one movie on the uk box office chart details of how hell mark his landmark birthday are under wraps his agent and publicist had no comment on his plans ill definitely have some sort of party he said in an interview hopefully none of you will be reading about it radcliffes earnings from the first five potter films have been held in a trust fund which he has not been able to touch despite his growing fame and riches the actor says he is keeping his feet firmly on the ground people are always looking to say kid star goes off the rails he told reporters last month but i try very hard not to go that way because it would be too easy for them his latest outing as the boy wizard in harry potter and the order of the phoenix is breaking records on both sides of the atlantic and he will reprise the role in the last two films  watch ireporter give her review of potters latest   there is life beyond potter however the londoner has filmed a tv movie called my boy jack about author rudyard kipling and his son due for release later this year he will also appear in december boys an australian film about four boys who escape an orphanage earlier this year he made his stage debut playing a tortured teenager in peter shaffers equus meanwhile he is braced for even closer media scrutiny now that hes legally an adult i just think im going to be more sort of fair game he told reuters email to a friend  copyright 2007 reuters all rights reservedthis material may not be published broadcast rewritten or redistributed

In [28]:
## Understanding
df["article"].apply(clean_text)

0         london england reuters  harry potter star dani...
1         editors note in our behind the scenes series c...
2         minneapolis minnesota cnn  drivers who were on...
3         washington cnn  doctors removed five small pol...
4         cnn   the national football league has indefin...
                                ...
287108    the nineyearold daughter of a black unarmed ma...
287109    legalising assisted suicide is a slippery slop...
287110    a group calling itself the women of the 99 per...
287111    most men enjoy a good pint of lager or real al...
287112    a facebook page seeking to preserve the black ...
Name: article, Length: 287113, dtype: object

In [29]:
import sys
!{sys.executable} -m pip install transformers sentencepiece

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in .\AppData\Roaming\Python\Python313\site-packages (5.13.0)
Requirement already satisfied: sentencepiece in .\AppData\Roaming\Python\Python313\site-packages (0.2.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in .\AppData\Roaming\Python\Python313\site-packages (from transformers) (1.22.0)
Requirement already satisfied: numpy>=1.17 in C:\ProgramData\anaconda3\Lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in C:\ProgramData\anaconda3\Lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in C:\ProgramData\anaconda3\Lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in .\AppData\Roaming\Python\Python313\site-packages (from transformers) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in .\AppData\Roaming\Python\Python313\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in C:\ProgramData\anaconda3\Lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.8.0 in .\AppData\Roaming\Python\Python313\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in C:\ProgramData\anaconda3\Lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.12.2)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: anyio in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.4.26)
Requirement already satisfied: httpcore==1.* in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in C:\ProgramData\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

In [30]:
import transformers
print(transformers.__version__)

5.13.0

## Import T5

In [31]:
import sys
!{sys.executable} -m pip install torch torchvision torchaudio

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: torch in .\AppData\Roaming\Python\Python313\site-packages (2.12.1)
Requirement already satisfied: torchvision in .\AppData\Roaming\Python\Python313\site-packages (0.27.1)
Requirement already satisfied: torchaudio in .\AppData\Roaming\Python\Python313\site-packages (2.11.0)
Requirement already satisfied: filelock in C:\ProgramData\anaconda3\Lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\ProgramData\anaconda3\Lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools<82 in C:\ProgramData\anaconda3\Lib\site-packages (from torch) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in C:\ProgramData\anaconda3\Lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in C:\ProgramData\anaconda3\Lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in C:\ProgramData\anaconda3\Lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in .\AppData\Roaming\Python\Python313\site-packages (from torch) (2024.6.1)
Requirement already satisfied: numpy in C:\ProgramData\anaconda3\Lib\site-packages (from torchvision) (2.1.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from torchvision) (11.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from jinja2->torch) (3.0.2)

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

In [32]:
from transformers import T5Tokenizer, T5ForConditionalGeneration

In [33]:
## Load the Tokenizer
tokenizer = T5Tokenizer.from_pretrained("t5-small")

In [34]:
## Model
model = T5ForConditionalGeneration.from_pretrained("t5-small")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

In [35]:
## First article
article = df["clean_article"][0]
print(article[:500])

london england reuters  harry potter star daniel radcliffe gains access to a reported 20 million 411 million fortune as he turns 18 on monday but he insists the money wont cast a spell on him daniel radcliffe as harry potter in harry potter and the order of the phoenix to the disappointment of gossip columnists around the world the young actor says he has no plans to fritter his cash away on fast cars drink and celebrity parties i dont plan to be one of those people who as soon as they turn 18 s

In [38]:
## T5 input create
input_text = "summarize: " + article

In [39]:
## Tokenize
inputs = tokenizer(
    input_text,
    return_tensors="pt",
    max_length=512,
    truncation=True
)

In [40]:
## Generate Summary
summary_ids = model.generate(
    inputs["input_ids"],
    max_length=60,
    min_length=20,
    num_beams=4,
    early_stopping=True
)

In [41]:
## Decode Summary
summary = tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print("Generated Summary:")
print(summary)

Generated Summary:
harry potter star daniel radcliffe says he has no plans to fritter his cash away on fast cars drink and celebrity parties. he says he is keeping his feet firmly on the ground people are always looking to say kid star

## (Model Evaluation)

In [42]:
index = 0

print("Original Article:\n")
print(df["article"][index][:1000])

print("\n\nHuman Summary:\n")
print(df["highlights"][index])

print("\n\nAI Summary:\n")
print(summary)

Original Article:

LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as soon as they turn 18, suddenly buy themselves a massive sports car collection or something similar," he told an Australian interviewer earlier this month. "I don't think I'll be particularly extravagant. "The things I like buying are things that cost about 10 pounds -- books and CDs and DVDs." At 18, Radcliffe will be able to gamble in a casino, buy a drink in a pub or see the horror film "Hostel: Part II," currently six places below his number one movie on the UK box office chart. Details of how


Human Summary:

Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday .
Young actor says he has no plans to fritter his cash away .
Radcliffe's earnings from first five Potter films have been held in trust fund .


AI Summary:

harry potter star daniel radcliffe says he has no plans to fritter his cash away on fast cars drink and celebrity parties. he says he is keeping his feet firmly on the ground people are always looking to say kid star

## ROUGE Evaluation

### Now we'll evaluate how close the AI summary is to the human summary using the ROUGE metric, which is the standard evaluation method for text summarization.

In [44]:
import sys

!{sys.executable} -m pip install evaluate rouge_score

Defaulting to user installation because normal site-packages is not writeable
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: datasets>=2.0.0 in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (2.21.0)
Requirement already satisfied: numpy>=1.17 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (3.8.0)
Requirement already satisfied: multiprocess in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in .\AppData\Roaming\Python\Python313\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.6.1)
Requirement already satisfied: huggingface-hub>=0.7.0 in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (1.22.0)
Requirement already satisfied: packaging in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (24.2)
Requirement already satisfied: absl-py in .\AppData\Roaming\Python\Python313\site-packages (from rouge_score) (2.4.0)
Requirement already satisfied: nltk in C:\ProgramData\anaconda3\Lib\site-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in C:\ProgramData\anaconda3\Lib\site-packages (from rouge_score) (1.17.0)
Requirement already satisfied: filelock in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in .\AppData\Roaming\Python\Python313\site-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: aiohttp in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (3.11.10)
Requirement already satisfied: pyyaml>=5.1 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.0)
Requirement already satisfied: idna>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp->datasets>=2.0.0->evaluate) (3.7)
Requirement already satisfied: click<9.0.0,>=8.4.2 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub>=0.7.0->evaluate) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub>=0.7.0->evaluate) (0.4.6)
Requirement already satisfied: anyio in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.7.0)
Requirement already satisfied: certifi in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (2025.4.26)
Requirement already satisfied: httpcore==1.* in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\ProgramData\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: sniffio>=1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.3.0)
Requirement already satisfied: joblib in C:\ProgramData\anaconda3\Lib\site-packages (from nltk->rouge_score) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in .\AppData\Roaming\Python\Python313\site-packages (from nltk->rouge_score) (2026.6.28)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2025.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (pyproject.toml): started
  Building wheel for rouge_score (pyproject.toml): finished with status 'done'
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=25024 sha256=cf530c78065027e804f456133711c9c1b9bd3ce433a96a1f281bb6691e59b9f2
  Stored in directory: c:\users\mohammed siyan\appdata\local\pip\cache\wheels\44\af\da\5ffc433e2786f0b1a9c6f458d5fb8f611d8eb332387f18698f
Successfully built rouge_score
Installing collected packages: rouge_score, evaluate

   ---------------------------------------- 0/2 [rouge_score]
   -------------------- ------------------- 1/2 [evaluate]
   -------------------- ------------------- 1/2 [evaluate]
   -------------------- ------------------- 1/2 [evaluate]
   -------------------- ------------------- 1/2 [evaluate]
   -------------------- ------------------- 1/2 [evaluate]
   ---------------------------------------- 2/2 [evaluate]

Successfully installed evaluate-0.4.6 rouge_score-0.1.2

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
  WARNING: The script evaluate-cli.exe is installed in 'C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

In [45]:
import sys

!{sys.executable} -m pip install --user evaluate rouge_score

Requirement already satisfied: evaluate in .\AppData\Roaming\Python\Python313\site-packages (0.4.6)
Requirement already satisfied: rouge_score in .\AppData\Roaming\Python\Python313\site-packages (0.1.2)
Requirement already satisfied: datasets>=2.0.0 in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (2.21.0)
Requirement already satisfied: numpy>=1.17 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (3.8.0)
Requirement already satisfied: multiprocess in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in .\AppData\Roaming\Python\Python313\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.6.1)
Requirement already satisfied: huggingface-hub>=0.7.0 in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (1.22.0)
Requirement already satisfied: packaging in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (24.2)
Requirement already satisfied: absl-py in .\AppData\Roaming\Python\Python313\site-packages (from rouge_score) (2.4.0)
Requirement already satisfied: nltk in C:\ProgramData\anaconda3\Lib\site-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in C:\ProgramData\anaconda3\Lib\site-packages (from rouge_score) (1.17.0)
Requirement already satisfied: filelock in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in .\AppData\Roaming\Python\Python313\site-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: aiohttp in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (3.11.10)
Requirement already satisfied: pyyaml>=5.1 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.0)
Requirement already satisfied: idna>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp->datasets>=2.0.0->evaluate) (3.7)
Requirement already satisfied: click<9.0.0,>=8.4.2 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub>=0.7.0->evaluate) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub>=0.7.0->evaluate) (0.4.6)
Requirement already satisfied: anyio in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.7.0)
Requirement already satisfied: certifi in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (2025.4.26)
Requirement already satisfied: httpcore==1.* in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\ProgramData\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: sniffio>=1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.3.0)
Requirement already satisfied: joblib in C:\ProgramData\anaconda3\Lib\site-packages (from nltk->rouge_score) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in .\AppData\Roaming\Python\Python313\site-packages (from nltk->rouge_score) (2026.6.28)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2025.2)

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

In [46]:
import evaluate
print(evaluate.__version__)

0.4.6

In [47]:
import sys
!{sys.executable} -m pip install evaluate rouge_score

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: evaluate in .\AppData\Roaming\Python\Python313\site-packages (0.4.6)
Requirement already satisfied: rouge_score in .\AppData\Roaming\Python\Python313\site-packages (0.1.2)
Requirement already satisfied: datasets>=2.0.0 in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (2.21.0)
Requirement already satisfied: numpy>=1.17 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (3.8.0)
Requirement already satisfied: multiprocess in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in .\AppData\Roaming\Python\Python313\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.6.1)
Requirement already satisfied: huggingface-hub>=0.7.0 in .\AppData\Roaming\Python\Python313\site-packages (from evaluate) (1.22.0)
Requirement already satisfied: packaging in C:\ProgramData\anaconda3\Lib\site-packages (from evaluate) (24.2)
Requirement already satisfied: absl-py in .\AppData\Roaming\Python\Python313\site-packages (from rouge_score) (2.4.0)
Requirement already satisfied: nltk in C:\ProgramData\anaconda3\Lib\site-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in C:\ProgramData\anaconda3\Lib\site-packages (from rouge_score) (1.17.0)
Requirement already satisfied: filelock in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in .\AppData\Roaming\Python\Python313\site-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: aiohttp in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (3.11.10)
Requirement already satisfied: pyyaml>=5.1 in C:\ProgramData\anaconda3\Lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\ProgramData\anaconda3\Lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.0)
Requirement already satisfied: idna>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp->datasets>=2.0.0->evaluate) (3.7)
Requirement already satisfied: click<9.0.0,>=8.4.2 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub>=0.7.0->evaluate) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in .\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub>=0.7.0->evaluate) (0.4.6)
Requirement already satisfied: anyio in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.7.0)
Requirement already satisfied: certifi in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (2025.4.26)
Requirement already satisfied: httpcore==1.* in C:\ProgramData\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\ProgramData\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: sniffio>=1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.3.0)
Requirement already satisfied: joblib in C:\ProgramData\anaconda3\Lib\site-packages (from nltk->rouge_score) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in .\AppData\Roaming\Python\Python313\site-packages (from nltk->rouge_score) (2026.6.28)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas->evaluate) (2025.2)

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

In [49]:
## Import evaluate
import evaluate

In [50]:
## Load ROUGE
rouge = evaluate.load("rouge")

Downloading builder script: 0.00B [00:00, ?B/s]

In [52]:
## Evaluate your summary
results = rouge.compute(
    predictions=[summary],
    references=[df["highlights"][0]]
)

print(results)

{'rouge1': np.float64(0.4), 'rouge2': np.float64(0.33333333333333337), 'rougeL': np.float64(0.37499999999999994), 'rougeLsum': np.float64(0.4)}

In [53]:
{
    'rouge1': 0.48,
    'rouge2': 0.27,
    'rougeL': 0.45,
    'rougeLsum': 0.45
}

{'rouge1': 0.48, 'rouge2': 0.27, 'rougeL': 0.45, 'rougeLsum': 0.45}

## Install Streamlit

In [54]:
import sys
!{sys.executable} -m pip install streamlit

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: streamlit in C:\ProgramData\anaconda3\Lib\site-packages (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in .\AppData\Roaming\Python\Python313\site-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (11.1.0)
Collecting protobuf<7,>=3.20 (from streamlit)
  Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: pyarrow>=7.0 in .\AppData\Roaming\Python\Python313\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in C:\ProgramData\anaconda3\Lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in C:\ProgramData\anaconda3\Lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\ProgramData\anaconda3\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in C:\ProgramData\anaconda3\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: attrs>=22.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\ProgramData\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in C:\ProgramData\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in C:\ProgramData\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl (437 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 7.35.1
    Uninstalling protobuf-7.35.1:
      Successfully uninstalled protobuf-7.35.1
Successfully installed protobuf-6.33.6

WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ill (C:\Users\MOHAMMED SIYAN\AppData\Roaming\Python\Python313\site-packages)

In [55]:
## Add this code to

            skip_special_tokens=True
        )
import streamlit as st
from transformers import T5Tokenizer, T5ForConditionalGeneration

# Load Model
@st.cache_resource
def load_model():
    tokenizer = T5Tokenizer.from_pretrained("t5-small")
    model = T5ForConditionalGeneration.from_pretrained("t5-small")
    return tokenizer, model

tokenizer, model = load_model()

# Title
st.title("📝 Text Summarization App")
st.write("Enter a long article and click Generate Summary.")

# Input
article = st.text_area("Enter Text", height=300)

# Button
if st.button("Generate Summary"):

    if article.strip() == "":
        st.warning("Please enter some text.")
    else:
        input_text = "summarize: " + article

        inputs = tokenizer(
            input_text,
            return_tensors="pt",
            max_length=512,
            truncation=True
        )

        summary_ids = model.generate(
            inputs["input_ids"],
            max_length=120,
            min_length=30,
            num_beams=4,
            early_stopping=True
        )

        summary = tokenizer.decode(
            summary_ids[0],
        st.subheader("Generated Summary")
        st.success(summary)

2026-07-06 14:51:06.976 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:07.809
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-07-06 14:51:07.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:07.812 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:08.327 Thread 'Thread-20': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:08.332 Thread 'Thread-20': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

2026-07-06 14:51:13.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:13.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.087 Session state does not function when running a script without `streamlit run`
2026-07-06 14:51:14.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-06 14:51:14.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.